"""
实验五配置：路径、仓库、关键词、API参数
"""

import os

# ============================================================
# 路径
# ============================================================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(BASE_DIR)

EXPERIMENT1_DIR = os.path.join(PROJECT_ROOT, "experiment1")
EXPERIMENT2_DIR = os.path.join(PROJECT_ROOT, "experiment2")
EXPERIMENT4_DIR = os.path.join(PROJECT_ROOT, "experiment4")
EXPERIMENT5_DIR = BASE_DIR

# 输入路径
EXPERIMENT1_DATASET_CSV = os.path.join(
    EXPERIMENT1_DIR, "results", "processed", "dataset.csv"
)
EXPERIMENT1_DATASET_JSON = os.path.join(
    EXPERIMENT1_DIR, "results", "processed", "dataset.json"
)
EXPERIMENT1_MERGED_RAW = os.path.join(PROJECT_ROOT, "raw", "merged_raw.json")

# 输出目录
RESULTS_RAW_DIR = os.path.join(EXPERIMENT5_DIR, "results", "raw")
RESULTS_PROCESSED_DIR = os.path.join(EXPERIMENT5_DIR, "results", "processed")
RESULTS_EVALUATION_DIR = os.path.join(EXPERIMENT5_DIR, "results", "evaluation")
FIGURES_DIR = os.path.join(EXPERIMENT5_DIR, "figures")

# 输出文件
AI_CANDIDATES_JSON = os.path.join(RESULTS_RAW_DIR, "ai_pr_candidates.json")
AI_COLLECTED_JSON = os.path.join(RESULTS_RAW_DIR, "ai_pr_collected.json")
AI_COLLECTED_CHECKPOINT = os.path.join(RESULTS_RAW_DIR, "ai_pr_collected_checkpoint.json")
AI_DATASET_SEED_CSV = os.path.join(RESULTS_PROCESSED_DIR, "ai_generated_dataset_seed.csv")
AI_DATASET_ENHANCED_CSV = os.path.join(
    RESULTS_PROCESSED_DIR, "ai_generated_dataset_enhanced.csv"
)
AI_DATASET_CSV = os.path.join(RESULTS_PROCESSED_DIR, "ai_generated_dataset.csv")
AI_PATCH_INDEX_SEED = os.path.join(RESULTS_PROCESSED_DIR, "ai_patch_index_seed.json")
AI_PATCH_INDEX = os.path.join(RESULTS_PROCESSED_DIR, "ai_patch_index.json")
AI_DETECTION_STATS_JSON = os.path.join(
    RESULTS_EVALUATION_DIR, "ai_detection_stats.json"
)
AI_DATASET_STATS_JSON = os.path.join(RESULTS_EVALUATION_DIR, "ai_dataset_stats.json")
SEED_DATASET_STATS_JSON = os.path.join(
    RESULTS_EVALUATION_DIR, "seed_dataset_stats.json"
)
PIPELINE_LOG = os.path.join(EXPERIMENT5_DIR, "results", "pipeline.log")

# 2.6.2 4×4 Prompt×Context 输出路径
AI_LLM_SAMPLE_50 = os.path.join(RESULTS_PROCESSED_DIR, "ai_llm_sample_50.csv")
AI_LLM_4X4_TASK_LIST = os.path.join(RESULTS_PROCESSED_DIR, "ai_llm_4x4_task_list.json")
LLM_4X4_RAW = os.path.join(os.path.dirname(RESULTS_PROCESSED_DIR), "predictions", "llm_4x4_raw_responses.jsonl")
LLM_4X4_PARSED = os.path.join(os.path.dirname(RESULTS_PROCESSED_DIR), "predictions", "llm_4x4_parsed_predictions.csv")
LLM_4X4_METRICS = os.path.join(RESULTS_EVALUATION_DIR, "llm_4x4_metrics.json")
LLM_4X4_HEATMAP = os.path.join(FIGURES_DIR, "09_llm_4x4_prompt_context_heatmap.png")

# 确保目录存在
for _d in [
    RESULTS_RAW_DIR,
    RESULTS_PROCESSED_DIR,
    RESULTS_EVALUATION_DIR,
    FIGURES_DIR,
]:
    os.makedirs(_d, exist_ok=True)

# ============================================================
# 仓库列表
# ============================================================
ORIGINAL_REPOS = [
    "microsoft/vscode",
    "huggingface/transformers",
    "facebook/react",
    "pandas-dev/pandas",
    "kubernetes/kubernetes",
]

EXTENDED_REPOS = [
    "vercel/next.js",
    "microsoft/playwright",
    "langchain-ai/langchain",
    "openai/openai-python",
    "microsoft/autogen",
]

ALL_REPOS = ORIGINAL_REPOS + EXTENDED_REPOS

# 每个仓库最多保留PR数，避免再次被单一仓库主导
MAX_PER_REPO = 80

# 采集时仓库优先级顺序：先原始仓库，再扩展仓库
REPO_PRIORITY = {
    repo: i for i, repo in enumerate(ALL_REPOS)
}

# ============================================================
# AI 检测关键词
# ============================================================
STRONG_KEYWORDS = [
    "copilot",
    "github copilot",
    "chatgpt",
    "gpt",
    "claude",
    "cursor",
    "codex",
    "code agent",
    "ai-generated",
    "generated by ai",
    "generated with",
    "co-authored-by: copilot",
    "openai",
    "deepseek",
    "qwen",
]

# 弱词 "ai" 需要配合上下文词
AI_CONTEXT_WORDS = [
    "generated",
    "agent",
    "copilot",
    "llm",
    "assisted",
    "powered",
]

# 检测字段
DETECTION_FIELDS = [
    "title",
    "body",
    "commit_messages",
    "label_names",
    "author",
    "review_comments_text",
]

# ============================================================
# GitHub API 设置
# ============================================================
# Token: 优先使用环境变量，其次使用此默认值
GITHUB_TOKEN = os.environ.get(
    "GITHUB_TOKEN",
    "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",
)
GITHUB_API_BASE = "https://api.github.com"

# 频率限制
SEARCH_RATE_LIMIT = 30       # Search API 每分钟请求数
CORE_RATE_LIMIT = 5000       # Core API 每小时请求数
RATE_LIMIT_BUFFER = 0.8      # 安全缓冲系数

# 搜索参数
SEARCH_PER_PAGE = 100
MAX_SEARCH_PAGES = 10        # GitHub最多返回1000条结果

# 多线程
MAX_WORKERS = 8
REQUEST_TIMEOUT = 30

# ============================================================
# 采集目标
# ============================================================
TARGET_TOTAL_SAMPLES = 300
MIN_ENHANCED_FOR_DEFAULT = 150

# ============================================================
# 随机种子
# ============================================================
RANDOM_SEED = 42

# ============================================================
# 日志
# ============================================================
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(PIPELINE_LOG, encoding="utf-8"),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger("experiment5")
