"""
实验一：构建数据集 — 集中配置文件
所有脚本共享的配置中心，无外部依赖。
"""

import os
import sys
from pathlib import Path

# ============================================================
# 目录路径
# ============================================================
EXPERIMENT_DIR = Path(__file__).parent.resolve()
DATA_DIR = EXPERIMENT_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
CHECKPOINT_DIR = DATA_DIR / "checkpoints"
FIGURES_DIR = EXPERIMENT_DIR / "figures"

# ============================================================
# GitHub API 配置
# ============================================================
API_BASE_URL = "https://api.github.com"

# Token：优先环境变量，其次 .token 文件
_TOKEN_FILE = EXPERIMENT_DIR / ".token"
_TOKEN_FROM_FILE = ""
if _TOKEN_FILE.exists():
    _TOKEN_FROM_FILE = _TOKEN_FILE.read_text().strip()
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN") or _TOKEN_FROM_FILE

# 5 个目标仓库
TARGET_REPOS = [
    ("kubernetes", "kubernetes"),
    ("pytorch", "pytorch"),
    ("microsoft", "vscode"),
    ("tensorflow", "tensorflow"),
    ("facebook", "react"),
]

PRS_PER_REPO = 300

# ============================================================
# 请求控制参数
# ============================================================
REQUEST_DELAY = 0.3        # 请求间最小间隔（秒），约3次/秒，总计~25分钟
MAX_RETRIES = 5            # 最大重试次数
RATE_LIMIT_BUFFER = 10     # 剩余请求数 ≤ 此值时休眠等待重置
PER_PAGE = 100             # 每页数量

# ============================================================
# AI 检测关键词
# ============================================================
AI_REVIEWER_KEYWORDS = [
    "ai", "copilot", "claude", "chatgpt", "codex", "gpt", "llm",
    "artificial intelligence", "copilot:summary", "ai-reviewed",
    "ai review", "automated review", "bot review", "ai-assisted",
]

AI_GENERATED_CODE_KEYWORDS = [
    "ai-generated", "generated by ai", "copilot", "codex",
    "chatgpt", "gpt-", "llm-generated", "ai generated",
    "generated by copilot", "generated by chatgpt",
    "ai-assisted code", "generated by llm",
]

# ============================================================
# 验证函数
# ============================================================
def validate_token():
    """验证 GitHub Token 是否已设置。"""
    if not GITHUB_TOKEN:
        print("=" * 60)
        print("错误：未设置 GITHUB_TOKEN 环境变量！")
        print("")
        print("GitHub API 匿名访问限制为 60 次/小时，")
        print("而本实验需要约 4500 次 API 调用。")
        print("")
        print("请按以下步骤操作：")
        print("1. 访问 https://github.com/settings/tokens")
        print("2. 点击 'Generate new token (classic)'")
        print("3. 无需勾选任何权限（仅访问公开仓库）")
        print("4. 复制生成的 token")
        print("5. 运行: export GITHUB_TOKEN=\"ghp_xxxxxxxxxxxx\"")
        print("=" * 60)
        return False
    return True


def ensure_dirs():
    """创建所有需要的目录。"""
    for d in [DATA_DIR, RAW_DATA_DIR, PROCESSED_DATA_DIR,
              CHECKPOINT_DIR, FIGURES_DIR]:
        d.mkdir(parents=True, exist_ok=True)


# 模块加载时自动创建目录
ensure_dirs()
